spring:
  application:
    name: midas-core
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

    # CONSUMER: read JSON -> Transaction
    consumer:
      group-id: midas-core
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.jpmc.midascore.foundation"
        # If tests don't send type headers, force the value type:
        spring.json.value.default.type: "com.jpmc.midascore.foundation.Transaction"

    # PRODUCER: write Transaction -> JSON
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# The tests look for this property to exist:
general:
  kafka-topic: midas.transactions

server:
  port: 8080

logging:
  level:
    com.jpmc.midascore: DEBUG
    org.springframework.kafka: DEBUG
    org.hibernate.SQL: DEBUG

